name: Upgrade Software Umami

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 6
  workflow_call:
    secrets:
      HOST:
        required: false
      USERNAME:
        required: false
      KEY:
        required: false
      PORT:
        required: false
      FINGERPRINT:
        required: false   

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Upgradeable packages of your system
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          script: apt list --upgradable

      - name: Update the list of available packages and their versions
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          script: apt-get update

      - name: Update the packages
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          fingerprint: ${{ secrets.FINGERPRINT }}
          script: apt-get upgrade -y